### PR TITLE
Add REDMINE_RMAGICK_FONT_PATH parameter for Redmine 4.0

### PR DESCRIPTION
**Pull request by urimaro**
I would like to propose adding the `REDMINE_RMAGICK_FONT_PATH` parameter to set `rmagick_font_path`.

ref. #439

### CODE REVIEW

**Comment by jcormier** [comment]
@urimaro You never answered my question last time.  Do we know if this is required for minimagick instead of rmagick?

**Comment by urimaro** [comment]
@jcormier 
I'm sorry for not answering your question.
I've checked that Redmine 4.0 hasn't used the MiniMagick yet.
https://github.com/redmine/redmine/blob/656c0db0cc3074804726c0f9a0258d7a81d64696/config/configuration.yml.example#L202
https://redmine.org/projects/redmine/wiki/Changelog

In the future, Redmine 4.0 might be going to use the MiniMagick.
Until then, I think we don't need to consider the MiniMagick for Redmine 4.0.

I will create a PR for Redmine 4.1, which considers the MiniMagick because it has used the MiniMagick instead of the RMagick.

**Comment by jcormier** [comment]
Thanks @urimaro.  I ended up merging the 3.4-stable branch into the 4.0-stable branch which also found a few other commits that 4.0-stable was missing

See 4.0.7-1 https://github.com/sameersbn/docker-redmine/blob/4.0-stable/Changelog.md

**Comment by jcormier** [comment]
Will merge 4.0-stable into master and rename the rmagick_font_path to minimagick_font_path

**Comment by jcormier** [comment]
@urimaro I pushed changes to master branch, would you be able to test it?

**Comment by urimaro** [comment]
Thank you, @jcormier.
I'll test that we can specify a font in the master branch.

**Comment by urimaro** [comment]
@jcormier 
I checked png files applied the font specified in the file.

a-gantt

**Comment by jcormier** [comment]
Released 4.1.1-7

**Pull request closed without merging**
