### PR TITLE
Allow setting email FROM fild via env like in your gitlab image with …

### PR DESCRIPTION
**Pull request by frank-dspeed**
…GITLAB_MAIL

Added fild for Setting Email via ENV

### CODE REVIEW

**Comment by sameersbn** [comment]
have you tested this change?

**Comment by frank-dspeed** [comment]
no not realy but it should work because i edited it from hand in the file and it worked

**Comment by sameersbn** [comment]
you missed adding the `sed` command to perform the substitution. 
also can you please used double braces in the template `{{}}`

**Comment by frank-dspeed** [comment]
ya i tsted it it isnt working the syntax was a bit wrong need to fix this up

**Comment by frank-dspeed** [comment]
i added the sed line but still dont working can you watch whats wrong?

**Comment by frank-dspeed** [comment]
http://www.redmine.org/projects/redmine/wiki/EmailConfiguration
tells advanced config is here
http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
and there is the info that this default options thing from: sets what email get used di di implamented it wrong?

**Comment by sameersbn** [comment]
Does the "Emission email address" setting in the Redmine UI achieve this?

email_from

**Comment by frank-dspeed** [comment]
Your right sorry i didnt remembered the issu the email notifications setting is the only working way my patch even dont worked but the setting realy did work :dancer:

**Comment by frank-dspeed** [comment]
I suggest realy to add that point to the documentation many people will search for it probally :)

**Comment by sameersbn** [comment]
I don't think we can document that stuff here. probably a link to redmine docs should suffice.

**Pull request closed without merging**
