### PR TITLE
Update baseimage to ubuntu 20.04

### PR DESCRIPTION
**Pull request by sachilles**
The base image for ubuntu is already outdated. This pull request includes an update of the base image and adjustments of the used packages.

### CODE REVIEW

**Comment by jcormier** [comment]
The change in ubuntu version should be mentioned in the Changelog as well as the explicit package version changes.  Otherwise, I think it looks good.

**Comment by sachilles** [comment]
Should the changes be listed along with the update of Redmine to version 4.1.2? And should all packages be named individually, or is a remark like 'update system packages' sufficient?

**Comment by sachilles** [comment]
Hopefully, the draft will fit the ideas.

**Comment by jcormier** [comment]
That should be good enough, people can look at the diffs if they want to know which packages got upgraded.

Have you been able to run redmine using these updates?  Looking for a documented confirmation that you have tried these changes.

**Comment by sachilles** [comment]
I'm using the updated version of redmine formerly using the "old" and now using the "new" base image. So far, I don't have any issues.

**Comment by jcormier** [comment]
Looks good to me

**Pull request merged**
