### PR TITLE
Add support for setting Access-Control-Allow-Origin header

### PR DESCRIPTION
**Pull request by sandratatarevicova**
This PR adds support for setting `Access-Control-Allow-Origin` header, see #147

### CODE REVIEW

**Comment by jcormier** [comment]
You need to move the add_header to outside the location as it will remove all headers from parent scopes.
https://www.peterbe.com/plog/be-very-careful-with-your-add_header-in-nginx

With your change we lose the strict-transport-security and x-content-type-options headers.

```diff
--- /tmp/before.txt     2020-03-10 09:53:57.093153254 -0400
+++ /tmp/after.txt      2020-03-10 09:54:15.152799766 -0400
@@ -1,7 +1,7 @@
  $ curl -I https://localhost:10445 -k
 HTTP/2 200
 server: nginx
-date: Tue, 10 Mar 2020 13:49:22 GMT
+date: Tue, 10 Mar 2020 13:53:09 GMT
 content-type: text/html; charset=utf-8
 x-frame-options: SAMEORIGIN
 x-xss-protection: 1; mode=block
@@ -9,11 +9,10 @@
 x-download-options: noopen
 x-permitted-cross-domain-policies: none
 referrer-policy: strict-origin-when-cross-origin
-etag: W/"90280d16b7a6bc4ddd66a502f31d370a"
+etag: W/"6e0215a7d50353a2e9f2fd2b7f9f4f92"
 cache-control: max-age=0, private, must-revalidate
-set-cookie: _redmine_session=UTNRcXVSQjF1eU8rVis0TVNuY1BHa2o0bEd3K21VdFRTTmJBOXB5ZDFpTDNUYkdEOHdJS0psSXNCVDRXdTV5ZWErenUwbGNMZTdmQW15SUdkTDRaWDdFTXVLdDN4R0hUSk9FWG04WWRqU1NYMUE2VUFFMjh2TEd4enhwTFhtcjBnbS80b3NFd2R5cHRTaXQzZFc2ajZsd0tOWnBUYjdLaFAwbGFuWUw0SWoySk9TZi9EWTUxck14bHhnbkRJWGhCLS0zdDNpTEYwY0JlQ2xwL2pocXlqTytnPT0%3D--d7e75ffc2f17864b03673b2f887f81c14677c0b4; path=/; secure; HttpOnly
-x-request-id: 00fda2d2-2990-4c21-a1d0-b61495d8d658
-x-runtime: 0.016412
-strict-transport-security: max-age=31536000;
-x-content-type-options: nosniff
+set-cookie: _redmine_session=SmdjS3pNdFVJRHVJUmV2U1N5Y1FMTjdxV2d4K1lScHpaTlVXellmak94MytwWUdBZkVLRlNrUE1uRElNZWRUVVZpSEJkNzhCZFRrWG1UV1hPU1p5bkFKTG1qMWFHQWpmOXlabG1OUEYwNVVKTWZkQVJwSlB4NzU0bVJsLzV2bjJVS1l6bkRoeURjQTRrT1ZieXZ3VzRXZXpxd3NuNkYyb3IyNDdRazI5dTduc3kxSStLcCtpSFVlVzNjdGFIaEVuLS0wWTFIWm45R3pFcWJHU21lL2V4elRBPT0%3D--5e6f3041e1192b221def14acc8964a05f3f04fc4; path=/; secure; HttpOnly
+x-request-id: e6a826c3-327a-4d5d-90ea-7b28a105dabe
+x-runtime: 0.766692
+access-control-allow-origin: test
```

**Comment by sandratatarevicova** [comment]
Fixed.

**Comment by jcormier** [comment]
Cool I'll give it a test.  Looking at the original issue #147, is there a reason to include or not include the other headers he did?

```
    add_header Access-Control-Allow-Origin $cors_origin_header always;
    add_header Access-Control-Allow-Credentials $cors_cred;
    add_header Access-Control-Allow-Methods "GET, POST, PUT, OPTIONS, HEAD";
    add_header Access-Control-Allow-Headers "Authorization, Origin, X-Requested-With, Content-Type, Accept, X-Redmine-API-Key";
```

**Comment by sandratatarevicova** [comment]
I have added the headers from #147. There are also othere CORS headers, but I think this should be sufficient for now (or at least for our use case it is 🙂 ). We can add other headers later if necessary.

**Comment by jcormier** [comment]
Great thanks

**Pull request merged**
