### PR TITLE
Added description of backup and restore to MySQL section.

### PR DESCRIPTION
**Pull request by dns2utf8**

### CODE REVIEW

**Comment by sameersbn** [comment]
@dns2utf8 will merge this PR as soon I can verify that the restore operation works. Thanks for the PR.

**Comment by dns2utf8** [comment]
You are welcome. I used this to migrate from one machine to an other.

**Comment by sameersbn** [comment]
@dns2utf8 do you think these instructions will be better placed in the readme of mysql image? We can refer to the instructions in this readme.

**Comment by dns2utf8** [comment]
@sameersbn I would add them on both descriptions, since it is realy usefull.

Regards

**Comment by sameersbn** [comment]
@dns2utf8 instructions for postgresql users would be great

**Comment by sameersbn** [comment]
PSA: In the `latest` versions i have added inbuild backup and restore functionality

**Pull request merged**
