### PR TITLE
Upgrade redmine from 3.4.7 to 4.0.0

### PR DESCRIPTION
**Pull request by obsessionsys**

### CODE REVIEW

**Comment by jcormier** [comment]
Note you can update a branch without deleting the pull request and github will detect the changes.

**Comment by obsessionsys** [comment]
I apologize for close this pull-request, trying to fix it.
Sorry.

**Comment by jcormier** [comment]
Alright no worries

**Comment by jcormier** [comment]
Would you be willing to test the update to ruby 2.5?

**Comment by obsessionsys** [comment]
At the moment I have made a full testing of the assembled Docker container in a bundle of redmine+mysql. All scripts for migration of DB and plugins were successful.
I tested redmine update from version 3.4.7 c rgloader () + plugins: a_common_libs custom_menu global_roles ldap_users_sync magic_my_page redmine_issue_tabs rm_business_time service_desk unread_issues
clear_plan extra_queries goals luxury_buttons redmine_budget redmine_sender rm_user_mentions under_construction usability
For my purpose I updated the ruby container to version 2.4, I did not change anything in the repository.
Most of the plugins are commercial and paid from RM+ (http://rmplus.pro)
 There were no problems with the migration and updating 
Prior to the update to version 4.0.0, I converted the DBMS from PostgreSQL to MySQL (bash script + small manual editing) since RM+ assures full compatibility with MySQL.
Currently, the sameersbn/redmine:4.0.0 + sameersbn/mysql:5.7.24 bundle is already running on production, no errors were detected.  
What should I do next? What tests should be executed?

**Pull request merged**
