### PR TITLE
Do not send HSTS header over plain http

### PR DESCRIPTION
**Pull request by J0WI**
See RFC 6797 Section 7.2
https://tools.ietf.org/html/rfc6797#section-7.2

### CODE REVIEW

**Comment by sameersbn** [comment]
@J0WI actually HSTS headers are added only if HTTPS is enabled either natively or via  a load-balancer. See https://github.com/sameersbn/docker-redmine/blob/master/assets/runtime/functions#L476-L486. If you use the image without SSL termination, HSTS headers will not be added.

**Comment by J0WI** [comment]
So, the only reason why the header exist in the [non HTTPS template](https://github.com/sameersbn/docker-redmine/blob/master/assets/runtime/functions#L484) is to [remove](https://github.com/sameersbn/docker-redmine/blob/master/assets/runtime/functions#L484) it?

If so both lines should be removed, because they are useless.

**Comment by sameersbn** [comment]
If user configures ssl termination at the load balancer the header will be added.

**Comment by J0WI** [comment]
Shouldn't the balancer add the header then?

**Comment by sameersbn** [comment]
true. but i am not sure if all load balancers allow configuring it

**Pull request merged**
