### PR TITLE
Updated: Apt Clean up to make img smaller

### PR DESCRIPTION
**Pull request by frank-dspeed**

### CODE REVIEW

**Comment by sameersbn** [comment]
@frank-dspeed the base `ubuntu:14.04` image does this by default, see `/etc/apt/apt.conf.d/docker-clean`.

**Comment by frank-dspeed** [comment]
This can't be realy true have tested it got diffrent results with the original base img i know tianons change but you can test it your self you get diffrent img size

**Comment by sameersbn** [comment]
@frank-dspeed I see no difference what so ever. the `apt-get clean` command is supposed to affect the `/var` directory, particularly the `/var/cache` directory. Since you insist, here is my test.

```bash
<- docker exec -it redmine bash
<- du -s /var
-> 21156	/var
<- apt-get clean
<- du -s /var
-> 21156	/var
```
As you can see, there are no changes in the size of the `/var` directory. I cannot comment on why you are seeing changes in the image size, but I am sure we do not need to explicitly specify `apt-get clean` because it is part of the default apt configuration in the docker ubuntu images.

P.S. `apt-get clean` used to be called earlier, since the base image now does it by default the command was removed from the dockerfile.

**Comment by sameersbn** [comment]
@frank-dspeed FYI,

Here is the before and after sizes of the effect of `apt-get clean` in the docker file

```bash
# BEFORE
sameersbn/redmine            latest              25c4044d1f2e        5 days ago          695.8 MB

# AFTER
sameersbn/redmine            latest              8b70e7507af0        6 seconds ago       695.9 MB
```

**Comment by frank-dspeed** [comment]
wirred maybe there is then a older ubuntu base img in my registry

**Pull request closed without merging**
