### PR TITLE
Upgrade the 3.2-stable branch to Redmine 3.2.8

### PR DESCRIPTION
**Pull request by flaudisio**
Hi,

I've made the upgrade path from 3.2.5 to 3.2.8 and upgraded the base image to version `14.04.20171024`. Tested locally without any problems.

### CODE REVIEW

**Comment by jcormier** [comment]
With this update git version 2.14.1 is now being installed.  You should pull in the following commits for a work around.

https://github.com/sameersbn/docker-redmine/commit/619107268c499bee4ea5cdb10fc515bb5c63d6b5
https://github.com/sameersbn/docker-redmine/commit/f83db463ee6e953343c6391bc432037dc3bd7656

```
 $ docker run -it --rm sameersbn/redmine:3.2.8 git --version --no-color
error: unknown option `no-color'
usage: git version [<options>]

    --build-options       also print build options
```

**Comment by flaudisio** [comment]
Cherry-picked and rebased! Please let me know if any further changes are needed.

**Comment by jcormier** [comment]
Any reason you applied the first commit before the changes and the second after?  Both commits are related, the 2nd fixing the first.

**Comment by frank-dspeed** [comment]
@jcormier when the test works lets merge it no matter what.

**Pull request merged**
