### PR TITLE
Add avatar server URL configuration support

### PR DESCRIPTION
**Pull request by siberianlove**
Sometimes it's useful to specify a different avatar server, like in my case, where our company has its own Gravatar-compatible service with employee avatars.

Gravatar uses an email hash to map avatars, but companies quite often have business mail with their own domains, and they have some sort of requirements for employee IDs and avatars on corporate portals and services.

### CODE REVIEW

**Comment by jcormier** [comment]
Were you able to verify the default gravatar support still works?  I'm not sure how to test it.

**Comment by siberianlove** [comment]
Yes it works, i tested it. You can test it with administrator rights by going to Administration > Settings > Display or using url https://your-redmine/settings?tab=display
Redmine displays current used gravatar server. And by default it will be https://gravatar.com
Also you can enable "Use Gravatar user icons" checkbox and visit any user page. Users will have avatars with this checkbox enabled. And if you specify **REDMINE_AVATAR_SERVER_URL** value of this env will be displayed at Administration > Settings > Display page and redmine will use this gravatar server for displaying avatars.

default one:
image

https://seccdn.libravatar.org specified in REDMINE_AVATAR_SERVER_URL:
image

**Comment by jcormier** [comment]
Much appreciated

**Comment by jcormier** [comment]
Do you want this cherry-picked to any previous releases?

**Comment by jcormier** [comment]
Released in 5.1.2

**Comment by siberianlove** [comment]
> Do you want this cherry-picked to any previous releases?

> Released in 5.1.2

5.1.2 is enough for me, thanks a lot!

**Pull request merged**
